AirplaneTickets/Models/Shared/OperationResult.cs
namespace AirplaneTickets.Models.Shared
{
    public class OperationResult
    {
        public bool Succeeded { get; }
        public string[] Errors { get; }

        private OperationResult(bool succeeded, string[] errors)
        {
            Succeeded = succeeded;
            Errors = errors;
        }

        public static OperationResult Success()
        {
            return new OperationResult(true, Array.Empty<string>());
        }

        public static OperationResult Failure(params string[] errors)
        {
            return new OperationResult(false, errors);
        }
    }
}

AirplaneTickets/Controllers/FlightController.cs
using Microsoft.AspNetCore.Mvc;
using AirplaneTickets.Services.Interfaces;
using AirplaneTickets.Models.ViewModels;
using AirplaneTickets.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace AirplaneTickets.Controllers
{
    public class FlightController : Controller
    {
        private readonly IFlightService _flightService;

        public FlightController(IFlightService flightService)
        {
            _flightService = flightService;
        }

        [HttpGet]
        public IActionResult SearchFlights()
        {
            return View(new SearchFlightsViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> SearchFlights(SearchFlightsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var flights = await _flightService.SearchFlightsAsync(model);

                return View("ListFlights", flights);

            }

            return View(model);
        }

        public async Task<IActionResult> ShowFlight(Guid id)
        {
            var flight = await _flightService.GetFlightByIdAsync(id);

            return View(flight);
        }

        [Authorize(Roles="Agent")]
        [HttpGet]
        public IActionResult CreateFlight()
        {
            return View();
        }

        [Authorize(Roles = "Agent")]
        [HttpPost]
        public async Task<IActionResult> CreateFlight(CreateFlightViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _flightService.CreateFlightAsync(model);

                if (result.Succeeded)
                {
                    ModelState.Clear();
                    ViewBag.Message = "Flight added successfully.";

                    return View();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, result.Errors[0]);
                }
            }

            return View(model);
        }

        [Authorize(Roles = "Agent, Admin")]
        public async Task<IActionResult> ListFlights()
        {
            var flights = await _flightService.FetchAllFlightsAsync();

            return View(flights);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CancelFlight(Guid id)
        {
            var (flight, result) = await _flightService.CancelFlightByIdAsync(id);

            if (!result.Succeeded)
            {
                ViewBag.Error = result.Errors[0];
            }

            return View("ShowFlight", flight);
        }
    }
}

AirplaneTickets/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using AirplaneTickets.Services.Interfaces;
using AirplaneTickets.Models.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using AirplaneTickets.Models.Entities;
using Microsoft.Identity.Client;
using AirplaneTickets.Models.Enums;


namespace AirplaneTickets.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationService _reservationService;

        public ReservationController(IReservationService reservationService)
        {
            _reservationService = reservationService;
        }

        [Authorize(Roles = "Visitor")]
        [HttpGet]
        public async Task<IActionResult> CreateReservation(Guid flightId)
        { 
            var (reservation, result) = await _reservationService.GetFlightAndUserByIdsAsync(flightId, Guid.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value));

            if (!result.Succeeded)
            {
                return NotFound(result.Errors[0]);
            }

            ViewBag.Flight = reservation.Flight;
            ViewBag.User = reservation.User;

            var model = new CreateReservationViewModel
            {
                FlightId = reservation.FlightId,
                UserId = reservation.UserId
            };

            return View(model);
        }

        [Authorize(Roles = "Visitor")]
        [HttpPost]
        public async Task<IActionResult> CreateReservation(CreateReservationViewModel model)
        {
            var (reservation, result) = await _reservationService.GetFlightAndUserByIdsAsync(model.FlightId, model.UserId);

            ViewBag.Flight = reservation.Flight;
            ViewBag.User = reservation.User;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            (reservation, result) = await _reservationService.CreateReservationAsync(model);

            if (result.Succeeded)
            {
                return View("ShowReservation", reservation);
            }
            else
            {
                ViewBag.ErrorMessage = result.Errors[0];
            }

            return View(model);
        }

        [Authorize(Roles = "Visitor")]
        [HttpGet]
        public async Task<IActionResult> MyReservations()
        {
            var reservations = await _reservationService.GetReservationsByUserIdAsync(Guid.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value));

            return View("ListReservations", reservations);
        }

        [Authorize(Roles = "Agent")]
        [HttpGet]
        public async Task<IActionResult> ListReservations()
        {
            var reservations = await _reservationService.FetchAllReservationsAsync();

            return View(reservations);
        }
        

        [Authorize(Roles = "Agent")]
        [HttpPost]
        public async Task<IActionResult> ChangeReservationStatus(Guid reservationId, ReservationStatus newStatus)
        {
            var (reservation, result) = await _reservationService.ChangeReservationStatusByIdAsync(reservationId, newStatus);

            if (!result.Succeeded)
            {
                ViewBag.ErrorMessage = result.Errors[0];
            }

            return View("ShowReservation", reservation);
        }

        [Authorize(Roles = "Agent, Visitor")]
        [HttpGet]
        public async Task<IActionResult> ShowReservation(Guid id)
        {
            var reservation = await _reservationService.GetReservationByIdAsync(id);

            if (reservation == null)
            {
                return NotFound("Reservation not found.");
            }

            return View(reservation);
        }

    }
}

AirplaneTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Plane&Simple</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AirplaneTickets.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Plane & Simple Airways</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="SearchFlights">Search Flights</a>
                        </li>
                        @if (User.IsInRole("Visitor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="MyReservations">My Reservations</a>
                            </li>
                        }
                        @if (User.IsInRole("Agent"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="ListFlights">All Flights</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="CreateFlight">Add Flight</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="ListReservations">Reservations</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="ListFlights">All Flights</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="CreateAccount">Create Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ListAccounts">All Accounts</a>
                            </li>
                        }
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
@* 
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Plane & Simple Airways - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>